import pygame
import math


class Wheel:
    def __init__(
        self,
        local_position,
        steering=False,
        driven=False,
        grip=1.0,
        max_grip=1.0
    ):
        # Position relative to the center of the car
        self.local_position = pygame.Vector2(local_position)

        # Wheel configuration
        self.steering = steering
        self.driven = driven

        # Tire properties
        self.grip = grip
        self.max_grip = max_grip

        # Current steering angle
        self.steering_angle = 0.0

        # Handbrake
        self.handbrake = False

        # Debug information
        self.longitudinal_velocity = 0.0
        self.lateral_velocity = 0.0
        self.slip_angle = 0.0
        self.lateral_force = 0.0
        self.longitudinal_force = 0.0

    def get_position(self, car):
        """
        Get the wheel's position in world space.
        """

        return (
            car.position
            + self.local_position.rotate(-car.angle)
        )

    def get_velocity(self, car):
        """
        Get the velocity of the wheel.

        Because the car is rotating, the wheel's velocity
        is different from the velocity of the car's center.
        """

        r = self.local_position.rotate(-car.angle)

        return pygame.Vector2(
            car.velocity.x
            - car.angular_velocity * r.y,

            car.velocity.y
            + car.angular_velocity * r.x
        )

    def get_directions(self, car):
        """
        Get the forward and sideways directions of the wheel.
        """

        # Car's forward direction
        forward = pygame.Vector2(1, 0).rotate(
            -car.angle
        )

        # Apply steering
        forward = forward.rotate(
            -self.steering_angle
        )

        # Perpendicular direction
        right = pygame.Vector2(
            -forward.y,
            forward.x
        )

        return forward, right

    def calculate_forces(
        self,
        car,
        throttle,
        brake,
        dt
    ):
        """
        Calculate all forces generated by this wheel.

        Returns:
            force, torque
        """

        # -------------------------------------------------
        # Wheel velocity
        # -------------------------------------------------

        wheel_velocity = self.get_velocity(car)

        # -------------------------------------------------
        # Wheel directions
        # -------------------------------------------------

        forward, right = self.get_directions(car)

        # -------------------------------------------------
        # Velocity components
        # -------------------------------------------------

        longitudinal_velocity = (
            wheel_velocity.dot(forward)
        )

        lateral_velocity = (
            wheel_velocity.dot(right)
        )

        self.longitudinal_velocity = longitudinal_velocity
        self.lateral_velocity = lateral_velocity

        # -------------------------------------------------
        # Slip angle
        # -------------------------------------------------

        speed = abs(longitudinal_velocity)

        if speed > 0.1:

            self.slip_angle = math.atan2(
                lateral_velocity,
                speed
            )

        else:
            self.slip_angle = 0.0

        # -------------------------------------------------
        # Lateral tire force
        # -------------------------------------------------

        lateral_force = (
            -lateral_velocity
            * self.grip
            * car.tire_stiffness
        )

        # Handbrake dramatically reduces rear grip
        if self.handbrake:

            lateral_force *= car.handbrake_grip

        # Limit tire force
        max_lateral_force = (
            self.max_grip
            * car.tire_grip
        )

        lateral_force = max(
            -max_lateral_force,
            min(
                max_lateral_force,
                lateral_force
            )
        )

        self.lateral_force = lateral_force

        # -------------------------------------------------
        # Engine force
        # -------------------------------------------------

        longitudinal_force = 0.0

        if self.driven:

            longitudinal_force += (
                throttle
                * car.engine_force
            )

        # -------------------------------------------------
        # Braking
        # -------------------------------------------------

        if brake > 0.0:

            # Direction opposite to wheel movement
            if abs(longitudinal_velocity) > 0.1:

                longitudinal_force += (
                    -math.copysign(
                        brake * car.brake_force,
                        longitudinal_velocity
                    )
                )

        self.longitudinal_force = longitudinal_force

        # -------------------------------------------------
        # Combine forces
        # -------------------------------------------------

        force = (
            forward * longitudinal_force
            + right * lateral_force
        )

        # -------------------------------------------------
        # Torque
        # -------------------------------------------------

        r = self.local_position.rotate(
            -car.angle
        )

        torque = (
            r.x * force.y
            - r.y * force.x
        )

        return force, torque